### PR TITLE
Format for valid domains is without protocol

### PR DESCRIPTION
**Pull request by mastef**
Uploading a `manifest.json` with a `http[s]://` type url in valid domains will fail with an error message.

### CODE REVIEW

**Comment by andrewconnell** [comment]
FYI @brandber ... this is a minor typo fix for a Teams module... LGTM & can be merged in.

**Comment by clearab** [comment]
The format for this field was changed, and this PR is no longer needed

**Comment by mastef** [comment]
@clearab Nope.

Error while reading manifest.json: Invalid value(s) specified for validDomains[0]: "https://7f0002ce.ngrok.io" For more information, please visit aka.ms/teamsdocs

**Comment by mastef** [comment]
Shouldn't be too hard to change the description [in Exercise 2 "Valid Domains"](
https://github.com/OfficeDev/TrainingContent/blob/master/Teams/02%20Tabs%20and%20Connectors/Lab.md#exercise-2-connectors) from :
```
  - **Valid domains**: *{enter the ngrok URL}*

    > NOTE: This field is used for actionable messages.
```
to
```
  - **Valid domains**: *{enter the ngrok domain name}*

    > (Do not enter the URI scheme, only the host. For example: `ab29ba51.ngrok.io`)
    > NOTE: This field is used for actionable messages.
```
as right now developers are taught to enter a wrong format.

And also [adjust it in the screenshot](https://github.com/OfficeDev/TrainingContent/blob/master/Teams/02%20Tabs%20and%20Connectors/Images/Exercise2-02.png).

**Comment by clearab** [comment]
@andrewconnell Can we add this to the list for the Q4 updates?

**Comment by andrewconnell** [comment]
@clearab we can update the module part, but I can't control the screenshot :)

**Comment by andrewconnell** [comment]
Actually, this is a PR so if @mastef wants to refresh his fork with the current changes in the repo, then resubmit the PR, you could merge to get the changes in now.

**Comment by clearab** [comment]
I'll take care of it.

**Comment by mastef** [comment]
I don't have time to keep fixing this PR. I'm closing it, and @clearab you can take over in #586. Good luck.

**Pull request closed without merging**
