### PR TITLE
O3652-13 Office Add-ins with Office UI Fabric: Adding new module.

### PR DESCRIPTION
**Pull request by TBag**
O3652-13 Office Add-ins with Office UI Fabric: Adding new module.

### CODE REVIEW

**Comment by jthake** [comment]
There is no slide deck in this commit?

**Comment by jthake** [comment]
Also I opened up completed exercise 2 and compiled and it fails with . This isn't a file length thign either it seems.

Severity	Code	Description	Project	File	Line	Suppression State
Error		This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\FabricUISample\packages\Microsoft.Net.Compilers.1.0.0\build\Microsoft.Net.Compilers.props.	FabricUISampleWeb	C:\Users\jthake\git\TbagFork\O3652\O3652-13 Office Add-ins with Office UI Fabric\Completed Exercises\Exercise02\FabricUISampleWeb\FabricUISampleWeb.csproj	757

**Comment by TBag** [comment]
No slide deck yet.  Working on it still.  Wanted to get all the code up there first.  I am looking into the error you are getting.  So far I cannot replicate it.

**Comment by TBag** [comment]
@jthake Just updated the Nuget packages and some paths to the packages folder.  Please try again.

**Comment by jthake** [comment]
still no joy here. Not quite sure why its doing that. If I create a new add-in in Visual STudio the project works fine but there seems to be some differences in packages.config

**Comment by TBag** [comment]
Please try deleting everything you have locally then downloading and trying again.

**Comment by jthake** [comment]
OK that fixed it ;-)
They compile fine.

**Pull request merged**
