### PR TITLE
O3652-1: Fixed typo & updated completed exercises. O3652-4: Changed some links to raw starter files.

### PR DESCRIPTION
**Pull request by Laskewitz**
There were some files missing due to the change from app > addin at the folders, so I fixed those too.

### CODE REVIEW

**Comment by Laskewitz** [comment]
@jthake Maybe this is more what you wanted? I chose the raw links so the visitors of dev.office.com won't even notice the files are on github.

**Comment by Laskewitz** [comment]
Still have an issue with the javascript highlighting in the lab.md though at exercise 3. Search for "After this step is complete, your Home.js file should match the following code listing." and you will find it.

**Comment by jthake** [comment]
I've updated soem instructions for each scneario in the issue #228

**Comment by Laskewitz** [comment]
I noticed, thanks. Will update pr tonight!



On Mon, Jan 25, 2016 at 9:50 AM -0800, "Jeremy Thake" <notifications@github.com<mailto:notifications@github.com>> wrote:


I've updated soem instructions for each scneario in the issue #228<https://github.com/OfficeDev/TrainingContent/issues/228>

**Comment by jthake** [comment]
Thank you for doign this @Laskewitz , I really appreciate it. Makes the lab a lot clearer on where to get the files!

**Pull request merged**
