### PR TITLE
Office Addins - Module 5: FY2019Q4 Quarterly refresh

### PR DESCRIPTION
**Pull request by andrewconnell**
- updated to reflect new project structure from Yeoman generator

### CODE REVIEW

**Comment by andrewconnell** [comment]
@davidchesnut ... I looked into the issue with the Vue section. 

It appears the Vue sample is having inconsistent execution based on the use of Office.onReady instead of Office.initialize. I *think* `Office.onReady` has a timing conflict with how Vue bootstraps to the UI. The Vue lab uses the regular “Office Add-in Task Pane project” template of the Yeoman generator, which now uses `Office.onReady`. 

We didn’t change this because if felt like the change from Office.initialize was deliberate in this template. I was unable to reproduce issues in Office Online and seemed to work just fine after one refresh in the Office Client. `Office.initialize` works just fine and is what is used in the React and Angular templates of the Yeoman generator. So, are you guys ok with us making the update in the Vue lab to change `Office.onReady` to `Office.initialize`?

**Comment by davidchesnut** [comment]
Hi @andrewconnell , it looks like there are more differences in the PR than just the initialization method. The .vue files were deleted for example. I think it should reflect the final code version after someone has completed all the steps in the manual. I'm checking on the onReady versus initialize. I'm not sure why the templates are not using onReady since that is the recommendation.

**Comment by andrewconnell** [comment]
@davidchesnut understood and agreed... once you let me know which way you'd like to go (`onReady`/`initialize`), I'll get things fixed and submitted...

**Comment by davidchesnut** [comment]
Okay. Since the steps in the lab also refer to initialize, how about we leave it as initialize for now. Chatted with the team and looks like they'll update the templates at some point to use onReady. So we can just change it to match when that happens in a later quarterly review. 

Thanks!

**Comment by andrewconnell** [comment]
@davidchesnut I think we got the `Office.onReady()` timing thing resolved as well as the other fixes. I just ran through the lab twice and everything looks good.

**Comment by davidchesnut** [comment]
@andrewconnell Thanks! I'm testing now. BTW: I discovered I needed to update webpack to "webpack-cli": "^3.3.5", or I ran into this [bug](https://stackoverflow.com/questions/56639025/how-to-solve-typeerror-process-getuid-is-not-a-function)...

Also these [demo instructions](https://github.com/OfficeDev/TrainingContent/tree/master/OfficeAddin/05%20Using%20modern%20JavaScript/Demos/03%20Office%20Add-in%20using%20VueJS) no longer match as some of the filenames changed in the template update. Can you update the instructions as well?

Thanks!

**Comment by davidchesnut** [comment]
@andrewconnell Yeah! It runs great! Thanks for the fixes! Would it be possible to also:
- update webpack-cli to ^3.3.5.
- update [demo steps](https://github.com/OfficeDev/TrainingContent/tree/master/OfficeAddin/05%20Using%20modern%20JavaScript/Demos/03%20Office%20Add-in%20using%20VueJS) for changed filenames and folder locations.
Thanks!

**Comment by andrewconnell** [comment]
The demo steps were updated... the link you're providing above is for the master branch in your repo. If you look at what I submitted, they are updated:
https://github.com/andrewconnell/TrainingContent/blob/fy2019q4-refresh-addins-m05/OfficeAddin/05%20Using%20modern%20JavaScript/Demos/03%20Office%20Add-in%20using%20VueJS/README.md

For the webpack issue you ran into, I didn't have that issue on the multiple machines we tested with. As that's what's in the default scaffolding created by the generator, that should be addressed by the team that owns that. I'll add a little extra comment for those who run into it though...

**Comment by davidchesnut** [comment]
@andrewconnell My bad, yep I was checking the wrong file, thank you.

Okay I'll go ahead and merge. Thanks for the updates on these!

**Pull request merged**
