### PR TITLE
FY2019Q2 module refresh - Teams m04

### PR DESCRIPTION
**Pull request by andrewconnell**
- verify lab and demos work as designed with dependency changes
- address minor typos

### CODE REVIEW

**Comment by BobGerman** [comment]
I'm still having trouble with the tabs in Lab 3.
I copied the files from LabFiles. The user is logged in every time because the upn variable isn't correctly scoped, but that's just a bit inefficient. The code fails trying to find function getProfileInformation(), which is not defined. The call to what might be the intended function (getData()) is commented out .. .but getData requires an access token and is passed an ID token.

The finished solution files and lab files should be the same except for changes specific to the student, such as the ngrok URL, yes? The hiring.html file is still different and neither version works at present.

ALSO - in order for this kind of authentication to work, it's necessary to enable implicit flow but I don't see that in the lab instructions. I enabled it and can do the Graph call in Postman, so I've verified my app is set up correctly. The lab instructions should include enabling implicit flow.

**Comment by andrewconnell** [comment]
Let me investigate...

**Comment by andrewconnell** [comment]
@BobGerman - I just ran through the whole lab & it looked like there was one code error (where it was trying to write to a `<div id="graph">` which was really `<div id="app">`) [that's been fixed](https://github.com/andrewconnell/TrainingContent/blob/fy2019q2-refresh-teams-m04/Teams/04%20Fundamentals%20of%20Microsoft%20Teams/Demos/03-tab-graph/solution/src/app/scripts/teamsApp1Tab.tsx#L71), and another part where the [token was being referenced incorrectly](https://github.com/andrewconnell/TrainingContent/blob/fy2019q2-refresh-teams-m04/Teams/04%20Fundamentals%20of%20Microsoft%20Teams/Demos/03-tab-graph/solution/src/app/scripts/teamsApp1Tab.tsx#L50-L51).

Everything else worked for me...

> The finished solution files and lab files should be the same except for changes specific to the student, such as the ngrok URL, yes? The hiring.html file is still different and neither version works at present.

Where are you seeing `hiring.html`? I don't see that file referencing anywhere in this lab in the lab instructions or built files.

> ALSO - in order for this kind of authentication to work, it's necessary to enable implicit flow but I don't see that in the lab instructions. I enabled it and can do the Graph call in Postman, so I've verified my app is set up correctly. The lab instructions should include enabling implicit flow.

Implicit flow is checked by default when using the App Registration Portal so this step isn't necessary. I verified this when I ran through this process myself just now.

**Comment by andrewconnell** [comment]
BTW @BobGerman, I assume when you say **lab3** you mean **exercise 3**. There is only one lab with three exercises in this module.

**Comment by andrewconnell** [comment]
BTW2 @BobGerman ... in reference to your `hiring.html` file comment above, keep in mind that each PR contains changes _only_ for a specific module. In this case, this PR only addresses m04... none of the other ones. At present, there are other PRs open for other Teams modules.

**Comment by BobGerman** [comment]
Sorry I didn't realize this PR was just for one of the labs. I was indeed referring to Lab 3 - Authentication, not exercise 3 or demo 3. I'm very much hoping for an improved Lab 3 so maybe I'm jumping out of hope for the issues... https://github.com/OfficeDev/TrainingContent/blob/master/Teams/03%20Authentication/LabFiles/hiringTeam.html is the file in question.

Thanks!

(BTW I registered new apps in v1, v2, and the stand-alone app registration portal and implicit wasn't checked in any of them - but no point hashing that out here. When Lab 3 is updated I'll follow it step by step and see what happens...)

THANKS!

**Comment by andrewconnell** [comment]
OK... good to know @BobGerman - M3 (_not lab 3_) is still a WIP but should have a PR for it later this week.

**Comment by pschaeflein** [comment]
@BobGerman - yes, the future Module 3 enables the implicit flow for logins for the tab. ;)

**Pull request merged**
