### PR TITLE
FY2020Q2 content refresh: "OfficeAddins - M01" 

### PR DESCRIPTION
**Pull request by andrewconnell**
- update module to use latest yeoman generator

### CODE REVIEW

**Comment by lindalu-MSFT** [comment]
Hi @andrewconnell Looks like there's a merge conflict with this file. Can you please resolve the conflict and let me know? ALSO, it would be of great help if you could put all your changes into a single PR instead of opening multiple ones. Thanks, lindalu

**Comment by lindalu-MSFT** [comment]
@andrewconnell Also, are you ready to merge from master to live and publish all this content?

**Comment by andrewconnell** [comment]
@lindalu-MSFT We don't put them in one big PR because each is for a package of changes for a specific module. This is because each team has to review the changes prior to merging them in, something they do.

I don't know what you mean about merging to live... there's no live branch in this repo. We've never done that in the past with this repo.

**None of these PRs were supposed to be merged yet... they were supposed to be reviewed by each engineering team who owns the topics & merges the PR's themselves.** This is how we've done it in previous quarters.

**Comment by andrewconnell** [comment]
@davidchesnut the code isn't copied from any repo... the code is what is generated by following the steps in the published tutorials from running `yo office` to create a new project. We didn't modify the readme's either because what's what `yo office` generates.

The idea for the demo folders is that they are snapshots of the project as you are following the lab (or in this case, the tutorials). So once you finish the first section ([up thru this step](https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/word-tutorial#replace-text-and-insert-text)), that would be the "demo 01", and so on for the other demos.

**Comment by davidchesnut** [comment]
@andrewconnell thanks for the explanation. Makes sense now! This looks good so I will merge.

**Pull request merged**
